= Java RELP Server Library (rlp_03)

rlp_03 implements RELP server in Java

== License
AGPLv3 with link:https://github.com/teragrep/rlp_03/blob/master/LICENSE#L665-L670[additional permissions] granted in the license.

== Features
Current

- Fast (~100 000 transactions in a second per thread)
- Secure (TLS)

== Usage
=== Setting dependencies
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <dependencies>
        <!-- this library -->
        <dependency>
            <groupId>com.teragrep</groupId>
            <artifactId>rlp_03</artifactId>
            <version>${see_latest_at_github}</version>
        </dependency>
    </dependencies>
</project>
----

NOTE: See https://github.com/teragrep/rlp_01[rlp_01] for relp client

NOTE: See https://github.com/teragrep/rlo_06[rlo_06] for syslog decoding

=== Examples

Dependencies for examples

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <dependencies>
        <!-- this library -->
        <dependency>
            <groupId>com.teragrep</groupId>
            <artifactId>rlp_03</artifactId>
            <version>${see_latest_at_github}</version>
        </dependency>
        <!-- rlp_01 for relp-client -->
        <dependency>
            <groupId>com.teragrep</groupId>
            <artifactId>rlp_01</artifactId>
            <version>${see_latest_at_github}</version>
        </dependency>
    </dependencies>
</project>
----

Server with shared handler for all connections. See ExampleRelpClient.java for client.

[source, java]
----
package com.teragrep.rlp_03.readme;

import com.teragrep.rlp_03.FrameContext;
import com.teragrep.rlp_03.Server;
import com.teragrep.rlp_03.ServerFactory;
import com.teragrep.rlp_03.config.Config;
import com.teragrep.rlp_03.delegate.*;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * For use cases in the README.adoc
 */
public class ReadmeTest {
    @Test
    public void testServerSetup() {
        int listenPort = 10601;
        int threads = 1; // processing threads shared across the connections
        Config config = new Config(listenPort, threads);

        /*
         * System.out.println is used to print the frame payload
         */
        Consumer<FrameContext> syslogConsumer = new Consumer<FrameContext>() {
            // NOTE: synchronized because frameDelegateSupplier returns this instance for all the parallel connections
            @Override
            public synchronized void accept(FrameContext frameContext) {
                System.out.println(frameContext.relpFrame().payload().toString());
            }
        };

        /*
         * DefaultFrameDelegate accepts Consumer<FrameContext> for processing syslog frames
         */
        DefaultFrameDelegate frameDelegate = new DefaultFrameDelegate(syslogConsumer);

        /*
         * Same instance of the frameDelegate is shared with every connection
         */
        Supplier<FrameDelegate> frameDelegateSupplier = new Supplier<FrameDelegate>() {
            @Override
            public FrameDelegate get() {
                System.out.println("Providing frameDelegate for a connection");
                return frameDelegate;
            }
        };

        /*
         * ServerFactory is used to create server instances
         */
        ServerFactory serverFactory = new ServerFactory(config, frameDelegateSupplier);

        Server server;
        try {
            server = serverFactory.create();
        }
        catch (IOException ioException) {
            throw new UncheckedIOException(ioException);
        }

        /*
         * One may use server.run(); or create the server into a new thread
         */
        Thread serverThread = new Thread(server);

        /*
         * Run the server
         */
        serverThread.start();

        /*
         * Wait for startup, server is available for connections once it finished setup
         */
        try {
            server.startup.waitForCompletion();
            System.out.println("server started at port <" + listenPort + ">");
        }
        catch (InterruptedException interruptedException) {
            throw new RuntimeException(interruptedException);
        }

        /*
         * Send Hello, World! via rlp_01
         */
        new ExampleRelpClient(listenPort).send("Hello, World!");

        /*
         * Stop server
         */
        server.stop();

        /*
         * Wait for stop to complete
         */
        try {
            serverThread.join();
        }
        catch (InterruptedException interruptedException) {
            throw new RuntimeException(interruptedException);
        }
        System.out.println("server stopped at port <" + listenPort + ">");

        /*
         * Close the frameDelegate
         */
        try {
            frameDelegate.close();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
----

If a separate handler is required for each connection which doesn’t need to be a thread-safe, create a new FrameDelegate in the Supplier<FrameDelegate>

[source, java]
----
        Supplier<FrameDelegate> frameDelegateSupplier = () -> {
            System.out.println("Providing frameDelegate for a connection");
            return new DefaultFrameDelegate(frameContext -> System.out.println(frameContext.relpFrame().payload().toString()));
        };
----

If a deferred handler is required for command processing, pass custom RelpEvent implementation to DefaultFrameDelegate via the Map<String, RelpEvent> constructor. See ReadmeDeferredTest.java for an example.

== Contributing
 
// Change the repository name in the issues link to match with your project's name
 
You can involve yourself with our project by https://github.com/teragrep/rlp_03/issues/new/choose[opening an issue] or submitting a pull request.
 
Contribution requirements:
 
. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).
 
Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].
 
=== Contributor License Agreement
 
Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.
 
You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories. 
